### ISSUE TITLE
Fix timeout when creating model and matrix

### ISSUE THREAD

**Issue by vigliensoni** [vigliensoni/R-VAE#13]
When saving a model, the matrix generation is taking a long time (30x30 = 900 sampled points). I'm getting the following error from Node:

```
node: stack Error: Max API Message Request timed out. id: u15569491665
    at makeError (/Applications/Ableton Live 10 Suite.app/Contents/App-Resources/Max/Max.app/Contents/Resources/C74/packages/Node For Max/source/lib/api/index.js:9:14)
    at Timeout._onTimeout (/Applications/Ableton Live 10 Suite.app/Contents/App-Resources/Max/Max.app/Contents/Resources/C74/packages/Node For Max/source/lib/api/index.js:178:12)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

I should take a look into asynchronous call to the function that is generating and saving the matrix.

**Comment by vigliensoni** [comment]
As of now, two sets of files are generated:

- A set for the visualizer:
> - model_XXX_YYYmodel-matrix-LS.data
> -  model_XXX_YYYmodel-matrix-vis.data
- A model for the latent space  as a TF model:
> - model.json
> - weights.bin

With the current version, I can do one or the other, not both at the same time for the timeout issue. I should look into async calls.

**Comment by vigliensoni** [comment]
The issue seems to have been fixed in b6c837a, but still testing.
